### ISSUE TITLE
csv_to_gpx does not use elevation and time

### ISSUE THREAD

**Issue by BogdanDIA** [nidhaloff/gpx-converter#5]
* gpx_converter version:
* Python version:3.8
* Operating System:Ubuntu20.04

### Description
When converting csv_to_gpx only latitude and longitude are taking in consideration. What about elevation, time, extensions?

I see that when converting from gpx to csv those are taking in consideration

**Comment by nidhaloff** [comment]
@Riemer17 did you add this implementation to your PR yesterday?

**Comment by Riemer17** [comment]
No, I tried to also make it possible to take the elevation and time in account when converting to GPX. But that did not work yet. I will try to fix that this week

**Comment by nidhaloff** [comment]
@Riemer17 Thanks! Please give me feedback about the progress if you could ;)

**Comment by mulka** [comment]
I'd love to see this as well.
