### ISSUE TITLE
Uppercase File Extension Not Supported

### ISSUE THREAD

**Issue by CF-FHB-X** [nidhaloff/gpx-converter#8]
* gpx_converter version: 1.7.3
* Python version: 3.8.10
* Operating System: Windows 10

### Description
It seems that the check for `input_extension` fails if your GPX file has an uppercase file extension.

### What I Did

```
from gpx_converter import Converter

gpx_file = r"C:\Data\Test_GPS_Data.GPX"
Converter(input_file=gpx_file).gpx_to_dataframe()
```
Throws the following:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-d42e2417745d> in <module>
----> 1 Converter(input_file=gpx_file).gpx_to_dataframe()

~\AppData\Local\programs\Anaconda3\envs\gpx\lib\site-packages\gpx_converter\base.py in gpx_to_dataframe(self, lats_colname, longs_colname, times_colname, alts_colname)
     59         """
     60         if self.input_extension != ".gpx":
---> 61             raise TypeError(f"input file must be a GPX file")
     62 
     63         if not lats_colname or not longs_colname:

TypeError: input file must be a GPX file
```

But running the following works:
```
from gpx_converter import Converter

gpx_file = r"C:\Data\Test_GPS_Data.GPX"
Converter(input_file=gpx_file.lower()).gpx_to_dataframe()
```

Should be as easy as changing that extension check to:
```
 if self.input_extension.lower() != ".gpx":
```

**Comment by nidhaloff** [comment]
@CF-FHB-X Thanks for the hint ;) 

You are right! do you want to fix this and make a PR or should I do it? I'm just asking because you basically posted the solution too :D, so feel free to make a PR if you want and I would happily review and accept it. If you don't want to then I will fix this myself ;)

**Comment by nidhaloff** [comment]
@CF-FHB-X I will fix this ;)

**Comment by CF-FHB-X** [comment]
Hey - sorry about that (been a busy last few days and missed the message!). Thanks for the fix!
